Add Ctests step on pull request
Also had to add SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread") to cmakelist because tests were failing with error undefined reference to `pthread_cond_clockwait'